GET http://localhost:3000/api/stats/product/avg?product=1&from=2021-09-28&to=2021-09-29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMDAwMDAwMDAiLCJpYXQiOjE2NjMzNjE3ODEsImV4cCI6MTY2MzM2NTM4MX0.6lYVjyzGjJvxcDzYbX7JrcJrFisf_QIFsJo4szACxu0
Content-Type: application/json