GET http://localhost:3000/api/stats/product?exports=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMDAwMDAwMDAiLCJpYXQiOjE2NjMyNDIwMDYsImV4cCI6MTY2MzI0NTYwNn0.rAukFXLuF0126pIrtxbP5Yv7j3BLTCnKwcFWemzscxI
Content-Type: application/json