version: '3.1'
services:
  app:
    build: .
    volumes:
      - .:/claranet
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: claranet
      POSTGRES_USER: claranet
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  data: